# 带[ ]括号的，就是多选，不带的就是单选,所有选项的 开对应true，关对应false，自行根据需要调整


# 目前调通了 job51 猎聘
boss:
  debugger: false # 开发者模式，默认为false即可
  sayHi: "您好！我是李国春，目前是哈尔滨理工大学与中国科学院自动化研究所联合培养的电子信息专硕在读生，研究方向为知识图谱、自然语言处理与大语言模型。在校期间不仅获得过校级一等奖学金，还在第十九届中国研究生电子设计竞赛东北赛区拿到二等奖，专业能力和实践能力都有扎实积累。此前有小米互联网业务部、中科院自动化研究所等单位的实习经历，参与过视频封面优选、知识图谱构建等项目，熟悉 Python/C/SQL 编程语言及 PyTorch、Flask、Docker 等工具，能快速适配技术岗需求。很希望能有机会进一步了解贵司秋招岗位的细节，感谢您的时间！" #必须要关闭boss的自动打招呼
  keywords: [ "大模型","搜索","广告","推荐","搜推","NLP","自然语言处理"] # 需要搜索的职位,会依次投递
  industry: [ "不限" ] # 公司行业，只能选三个，相关代码枚举的部分，如果需要其他的需要自己找
  cityCode: [ "北京","上海","杭州","南京","苏州","深圳","广州","武汉","长沙","重庆" ] # 只列举了部分,如果没有的需要自己找：目前支持的：全国 北京 上海 杭州 广州 深圳 成都 天津
  experience: [ "应届毕业生" ] # 工作经验："应届毕业生", "1年以下", "1-3年", "3-5年", "5-10年", "10年以上"
  jobType: "不限" #求职类型："全职", "兼职"
  salary: "20-50K" # 薪资（单选）："3K以下", "3-5K", "5-10K", "10-20K", "20-50K", "50K以上"
  degree: ["本科", "硕士"] # 学历: "初中及以下", "中专/中技", "高中", "大专", "本科", "硕士", "博士"
  scale: [ "100-499人", "500-999人", "1000-9999人", "10000人以上" ] # 公司规模："0-20人", "20-99人", "100-499人", "500-999人", "1000-9999人", "10000人以上"
  stage: [ "A轮", "B轮", "C轮", "D轮及以上", "已上市", "不需要融资" ] # "未融资", "天使轮", "A轮", "B轮", "C轮", "D轮及以上", "已上市", "不需要融资"
  expectedSalary: [ 20,50 ] #期望薪资，单位为K，第一个数字为最低薪资，第二个数字为最高薪资，只填一个数字默认为最低薪水
  waitTime: 10 #每投递一个岗位，等待几秒
  filterDeadHR: true # 是否过滤不活跃HR,该选项会过滤半年前活跃的HR
  enableAI: true # 开启AI检测与自动生成打招呼语
  sendImgResume: true # 是否发送图片简历
  deadStatus: [ "半年前活跃" ] # 过滤掉HR状态

job51:
  jobArea: [ "北京","上海","深圳","广州","成都" ]  #工作地区：目前只有【北京 成都 上海 广州 深圳】
  keywords: [ "大模型","搜索","广告","推荐","搜推","NLP","自然语言处理"] #关键词：依次投递
  salary: [ "不限" ] #薪资范围：只能选5个【"2千以下", "2-3千", "3-4.5千", "4.5-6千", "6-8千", "0.8-1万", "1-1.5万", "1.5-2万", "2-3万", "3-4万", "4-5万", "5万以上"】

lagou:
  keywords: [ "大模型","搜索","广告","推荐","搜推", "26校招","2026","NLP","自然语言处理"] #搜索关键词
  cityCode: "上海" #拉勾城市名没有限制,直接填写即可
  salary: "不限" #薪资【"不限","2k以下", "2k-5k", "5k-10k", "10k-15k", "15k-25k", "25k-50k", "50k以上"】
  scale: [ "不限" ] #公司规模【"不限","少于15人", "15-50人", "50-150人", "150-500人", "500-2000人", "2000人以上"】
  gj: "在校/应届,3年及以下"

liepin:
  cityCode: "全国" # 目前支持的：全国 北京 上海 广州 深圳 成都
  keywords: [ "大模型","搜索","广告","推荐","搜推","NLP","自然语言处理"]
  salary: "15$50" # 填 15$30 代表 15k-30k
  pubTime: "30" # 发布时间，单位天
  containsJobName: "大模型,算法,搜索,广告,推荐,搜推,NLP,自然语言处理,自然语言处理"
  excludeJobName: "实习,兼职,外包"

zhilian:
  cityCode: "全国"
  salary: "25001,35000" #薪资区间
  keywords: [ "大模型","搜索","广告","推荐","搜推","NLP","自然语言处理"]

ai:
  introduce: "您好！我是李国春，目前是哈尔滨理工大学与中国科学院自动化研究所联合培养的电子信息专硕在读生，研究方向为知识图谱、自然语言处理与大语言模型。在校期间不仅获得过校级一等奖学金，还在第十九届中国研究生电子设计竞赛东北赛区拿到二等奖，专业能力和实践能力都有扎实积累。此前有小米互联网业务部、中科院自动化研究所等单位的实习经历，参与过视频封面优选、知识图谱构建等项目，熟悉 Python/C/SQL 编程语言及 PyTorch、Flask、Docker 等工具，能快速适配技术岗需求。" #这是喂给AI的提示词，主要介绍自己的优势
  prompt: "我正在找2026秋招岗位，岗位方向是【%s】，目前需要投递的岗位是【%s】，岗位要求是【%s】。如果岗位要求和我的方向与经历基本符合，请帮我写一段给HR的招呼语，重点突出我的优势与岗位的匹配度，避免过多重复表述；  如果岗位与我的方向或经历完全不相关（如岗位注明毕业时间是2025年，则直接判定为不相关），则只返回false，不输出其他内容。  这是我之前写的招呼语：【%s】，你可以在此基础上根据岗位要求做针对性调整。  请直接输出最终招呼语内容，不要解释或分析。" #这是AI的提示词，可以自行修改

bot:
  is_send: true #开启企业微信消息推送
  is_bark_send: false
